"""
Django settings for a starter template project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from django_guid.integrations import CeleryIntegration

from configs.env import BASE_DIR
from logging_configs import LOGGING as BASE_LOGGING


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MY_APPS = []

THIRD_PARTY_APPS = [
    "django",
    "django_guid",
]

{% if cookiecutter.use_djangorestframework == "yes" %}
THIRD_PARTY_APPS += [
    "corsheaders",
    "rest_framework",
    "django_filters",
]
{% endif %}

{% if cookiecutter.use_drf_spectacular == "yes" %}
THIRD_PARTY_APPS += [
    "drf_spectacular",
]
{% endif %}

INSTALLED_APPS = THIRD_PARTY_APPS + MY_APPS + DJANGO_APPS


MIDDLEWARE = [
    "django_guid.middleware.guid_middleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

{% if cookiecutter.use_djangorestframework == "yes" %}
MIDDLEWARE += [
    "corsheaders.middleware.CorsMiddleware",
]
{% endif %}


ROOT_URLCONF = 'configs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configs.wsgi.application'

# Logging settings
LOGGING = BASE_LOGGING


{% if cookiecutter.use_djangorestframework == "yes" %}
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_RENDERER_CLASSES": [],
    "DEFAULT_VERSIONING_CLASS": "",
    "DEFAULT_SCHEMA_CLASS": "",
    "DEFAULT_PARSER_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "DEFAULT_FILTER_BACKENDS": [],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PAGINATION_CLASS": "",
    "PAGE_SIZE": 100,
}
{% endif %}


{% if cookiecutter.use_djangorestframework == "yes" %}
AUTHENTICATION_BACKENDS = []
{% endif %}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = ""

{% if cookiecutter.use_celery == "yes" %}
# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")  # change localhost to the service name of redis in docker-compose.yml
CELERY_RESULT_BACKEND = os.getenv("CELERY_BROKER_URL")  # change localhost to the service name of redis in docker-compose.yml
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Broker connection retry on startup
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_ALWAYS_EAGER = False  # Set to False for actual async processing in production
CELERY_TASK_EAGER_PROPAGATES = True
# Add this line to use django-celery-beat's DatabaseScheduler
CELERY_BEAT_SCHEDULER = ""
{% endif %}

{% if cookiecutter.use_drf_spectacular == "yes" %}
# drf-spectacular api documentation settings
SPECTACULAR_SETTINGS = {
    "TITLE": " {{ cookiecutter.project_name }}".title(),
    "DESCRIPTION": "{{ cookiecutter.description }}",
    "VERSION": "{{ cookiecutter.version }}",
    "SERVE_INCLUDE_SCHEMA": False,  # if using Swagger/Redoc view separately
    "COMPONENT_SPLIT_REQUEST": True,
    # Add auth info if using JWT
    "AUTHENTICATION_WHITELIST": [""],
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "",
                "scheme": "",
                "bearerFormat": "",
                "description": "",
            }
        }
    },
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,  # Saves token between page refreshes
    },
}
{% endif %}


DJANGO_GUID = {
    "GUID_HEADER_NAME": "Correlation-ID",
    "VALIDATE_GUID": True,
    "RETURN_HEADER": True,
    "EXPOSE_HEADER": True,
    "INTEGRATIONS": [CeleryIntegration(use_django_logging=True, log_parent=True)],
    "UUID_LENGTH": 28,
    "UUID_FORMAT": "hex",
}
