#!/usr/bin/env python

import os
import shutil
import subprocess

# Extract choices
REMOVE_DOCKER: bool = "{{ cookiecutter.use_docker }}".lower() == "no"
REMOVE_CELERY: bool = "{{ cookiecutter.use_celery }}".lower() == "no"
REMOVE_CLOUD_PROVIDER: bool = "{{ cookiecutter.cloud_provider}}".lower() == "none"

CLOUD_PROVIDER: str = "{{ cookiecutter.cloud_provider }}".lower()


def remove_file(filepath) -> None:
    """Safely removes a file relative to the generated project root."""
    full_path = os.path.join(os.getcwd(), filepath)
    if os.path.exists(full_path):
        os.remove(full_path)


def remove_directory(dirpath) -> None:
    """Safely removes a directory relative to the generated project root."""
    full_path = os.path.join(os.getcwd(), dirpath)
    if os.path.exists(full_path):
        shutil.rmtree(full_path)


def clean_docker_files() -> None:
    """Removes Docker-related files if the user opted out."""
    print("Removing Docker configuration files...")
    remove_file("compose.yaml")
    remove_file("Dockerfile")
    remove_file(".dockerignore")


def clean_celery_files() -> None:
    print("Removing Celery configuration components...")
    remove_file(os.path.join("configs/library_configs", "celery.py"))


def clean_aws_files() -> None:
    print("Removing AWS Cloud deployment configurations...")
    remove_file(os.path.join("configs/library_configs/deploy", "aws.py"))


def clean_azure_files() -> None:
    print("Removing AWS Cloud deployment configurations...")
    remove_file(os.path.join("configs/library_configs/deploy", "azure.py"))


def init_git():
    """Initializes a Git repository in the generated project directory."""
    pass


def handle_conditional_files() -> None:
    # If a user does not want Docker, remove Docker configuration files
    if REMOVE_DOCKER:
        clean_docker_files()

    # If a user does NOT want Celery, remove Celery configuration files
    if REMOVE_CELERY:
        clean_celery_files()

    # If cloud provider is None, clean up all cloud-specific deployment setups
    if REMOVE_CLOUD_PROVIDER:
        print("Removing Cloud deployment configurations...")
        clean_aws_files()
        clean_azure_files()
        remove_directory("configs/library_configs/deploy")
    else:
        # Extra cleanup: If they chose AWS, delete Azure files, and vice versa
        if CLOUD_PROVIDER == "aws":
            clean_azure_files()
        if CLOUD_PROVIDER == "azure":
            clean_aws_files()


def install_dependencies():
    """Configures Poetry to create a local virtual environment and installs packages."""
    print("\n--> Setting up virtual environment and installing dependencies via Poetry...")

    try:
        # 1. Force Poetry to create the virtual environment (.venv) inside the project directory
        subprocess.run(
            ["poetry", "config", "virtualenvs.in-project", "false"],
            check=True,
            capture_output=True
        )

        # 2. Run the full project installation process
        #  that resolves the pyproject.toml file generated by Cookiecutter
        subprocess.run(
            ["poetry", "install"],
            check=True,
            text=True
        )
        print("✅ Dependencies installed successfully via Poetry!")

    except (subprocess.CalledProcessError, FileNotFoundError):
        print("\n⚠️  WARNING: Automated dependency installation via Poetry failed.")
        print("This usually happens if Poetry is not globally accessible during generation.")
        print("You can manually set it up later by running: 'poetry install' in the project root.")


def main() -> None:
    handle_conditional_files()

    install_dependencies()

    print("\n🎉 Project files generated and cleaned up successfully!")


if __name__ == "__main__":
    main()
